spring:
  rabbitmq:
    host: 192.168.10.66
    port: 5672
    username: guest
    password: 123456
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 把消息确认模式改为手动确认
        prefetch: 1 # 每次只消费一个消息
logging:
  level:
    com.shiguang.mq.listener.MyMessageListener: info