spring:
  rabbitmq:
    host: 192.168.10.66
    port: 61000
    username: guest
    password: 123456
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 把消息确认模式改为手动确认
logging:
  level:
    com.shiguang.mq.listener.MyMessageListener: info